name: CD - Storage Account

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      RESOURCE_GROUP:
        required: true
      LOCATION:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Bicep artifacts
      uses: actions/download-artifact@v4
      with:
        name: Bicep-Artifact
        path: artifact

    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Check and create resource group if not exists
      run: |
        RG_EXISTS=$(az group exists --name ${{ secrets.RESOURCE_GROUP }})
        if [ "$RG_EXISTS" == "false" ]; then
          echo "Creating resource group ${{ secrets.RESOURCE_GROUP }}..."
          az group create --name ${{ secrets.RESOURCE_GROUP }} --location ${{ secrets.LOCATION }}
        else
          echo "Resource group ${{ secrets.RESOURCE_GROUP }} already exists."
        fi

    # - name: Deploy Resource Group Bicep file
    #   run: |
    #     az deployment sub create \
    #       --location ${{ secrets.LOCATION }} \
    #       --template-file artifact/resource-group.bicep \
    #       --parameters @artifact/parameters/${{ inputs.environment }}/resourcegroup/resourcegroup.bicepparam \
    #       --name ${{ inputs.environment }}-${{ github.run_id }}

    # - name: Deploy Storage Account Bicep file
    #   run: |
    #     az deployment group create \
    #       --resource-group ${{ secrets.RESOURCE_GROUP }} \
    #       --template-file artifact/templates/storageaccount.bicep \
    #       --parameters @${{ github.workspace }}/artifact/templates/parameters/${{ inputs.environment }}/storageaccount/storageaccount.bicepparam
    #       --name ${{ inputs.environment }}-${{ github.run_id }}

    - name: Validate parameter file exists
      run: |
        PARAM_FILE="artifact/templates/parameters/${{ inputs.environment }}/storageaccount/storageaccount.bicepparam"
        if [ ! -f "$PARAM_FILE" ]; then
          echo "ERROR: Parameter file not found: $PARAM_FILE"
          exit 1
        fi
        
    - name: Deploy Storage Account Bicep file
      run: |
        az deployment group create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --template-file artifact/templates/storageaccount/storageaccount.bicep \
          --parameters artifact/templates/parameters/${{ inputs.environment }}/storageaccount/storageaccount.bicepparam \
          --name ${{ inputs.environment }}-${{ github.run_id }}
      
