name: CI - Storage Account

on:
  pull_request:
    paths:
      - 'templates/storageaccount/**'
      - 'templates/parameters/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Display all files in working directory
      run: |
        ls -R ${{ github.workspace }}

    - name: Copy Bicep templates and parameters to staging directory
      run: |
        mkdir -p ${{ github.workspace }}/artifact
        cp -r templates/storageaccount/* ${{ github.workspace }}/artifact/
        cp -r templates/parameters/* ${{ github.workspace }}/artifact/

    - name: Upload Bicep artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Bicep-Artifact
        path: artifact/
