name: Azure Bicep Deployment

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    name: Deploy Bicep to Azure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure using Service Principal
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


    - name: Deploy Bicep file to Resource Group
      run: |
        az deployment group create --resource-group sample-demo-rg --template-file ./stoarge-account.bicep
